# Generated by Django 4.0.2 on 2022-02-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m3di', '0004_stringinteractionuniprot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissenseVarComCopy',
        ),
    ]
