# Generated by Django 3.2 on 2022-02-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basicbackup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uniprot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('protein_link', models.CharField(blank=True, max_length=300, null=True)),
                ('protein_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gene_name', models.CharField(blank=True, max_length=150, null=True)),
                ('gene_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'BasicBackup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pronameunique',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uniprot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('protein_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ProNameUnique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sigpep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_uniprot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signal_peptide', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'SigPep',
                'managed': False,
            },
        ),
    ]
