# Generated by Django 4.0.2 on 2022-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AaConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_name', models.CharField(blank=True, max_length=15, null=True)),
                ('one_let', models.CharField(blank=True, max_length=1, null=True)),
                ('thr_let_up', models.CharField(blank=True, max_length=3, null=True)),
                ('thr_let_low', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'aa_conversion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Basicinfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('protein_link', models.TextField(blank=True, null=True)),
                ('protein_name', models.TextField(blank=True, null=True)),
                ('gene_name', models.TextField(blank=True, null=True)),
                ('gene_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BasicInfo2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bindsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('substrate', models.CharField(blank=True, max_length=60, null=True)),
                ('bs_position', models.IntegerField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BindSite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domainnameunique',
            fields=[
                ('dm_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'DomainNameUnique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domains2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('protein_name', models.TextField(blank=True, null=True)),
                ('domain_name', models.TextField(blank=True, null=True)),
                ('dom_start', models.IntegerField(blank=True, null=True)),
                ('dom_end', models.IntegerField(blank=True, null=True)),
                ('eco', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Domains2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domainsrev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('protein_name', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dm_start', models.IntegerField(blank=True, null=True)),
                ('dm_end', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DomainsRev',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evicodes',
            fields=[
                ('eco', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('evidence_link', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EviCodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FkProDom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('dm_id', models.IntegerField(blank=True, null=True)),
                ('dm_start', models.IntegerField(blank=True, null=True)),
                ('dm_end', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fk_Pro_Dom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genelink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.TextField(blank=True, null=True)),
                ('gene_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GeneLink',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'GeneName',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Missense3DVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot', models.CharField(blank=True, max_length=10, null=True)),
                ('posuniprot', models.IntegerField(blank=True, null=True)),
                ('pdbpos', models.IntegerField(blank=True, null=True)),
                ('res_wt', models.CharField(blank=True, max_length=4, null=True)),
                ('res_mut', models.CharField(blank=True, max_length=4, null=True)),
                ('missensepred', models.CharField(blank=True, max_length=50, null=True)),
                ('missense_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Missense3D_Var',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MissenseVarCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot', models.CharField(blank=True, max_length=10, null=True)),
                ('posuniprot', models.IntegerField(blank=True, null=True)),
                ('pdbpos', models.IntegerField(blank=True, null=True)),
                ('res_wt', models.CharField(blank=True, max_length=4, null=True)),
                ('res_mut', models.CharField(blank=True, max_length=4, null=True)),
                ('missensepred', models.CharField(blank=True, max_length=50, null=True)),
                ('missense_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Missense_Var_Com',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('env_s', models.IntegerField(blank=True, null=True)),
                ('env_e', models.IntegerField(blank=True, null=True)),
                ('pfam_id', models.CharField(blank=True, max_length=10, null=True)),
                ('pfam_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('bit', models.IntegerField(blank=True, null=True)),
                ('e_value', models.CharField(blank=True, max_length=30, null=True)),
                ('clan', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Pfam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pfamdemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('align_s', models.IntegerField(blank=True, null=True)),
                ('align_e', models.IntegerField(blank=True, null=True)),
                ('env_s', models.IntegerField(blank=True, null=True)),
                ('env_e', models.IntegerField(blank=True, null=True)),
                ('pfam_id', models.CharField(blank=True, max_length=10, null=True)),
                ('pfam_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('hmm_s', models.IntegerField(blank=True, null=True)),
                ('hmm_e', models.IntegerField(blank=True, null=True)),
                ('hmm_len', models.IntegerField(blank=True, null=True)),
                ('bit', models.IntegerField(blank=True, null=True)),
                ('e_value', models.CharField(blank=True, max_length=30, null=True)),
                ('clan', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'PfamDemo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Primtoalias',
            fields=[
                ('primtoalias_id', models.AutoField(db_column='PrimToAlias_id', primary_key=True, serialize=False)),
                ('og_uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('alias', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'PrimToAlias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pronames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('protein_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ProNames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prosite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prosite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proteinlink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uniprot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('protein_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'ProteinLink',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ptms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptm_uniprot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.IntegerField(blank=True, null=True)),
                ('aa_one', models.CharField(blank=True, max_length=1, null=True)),
                ('ptm_type', models.CharField(blank=True, max_length=100, null=True)),
                ('eco', models.CharField(blank=True, max_length=100, null=True)),
                ('source_link', models.CharField(blank=True, max_length=300, null=True)),
                ('aa', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'PTMs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ptmsdemo',
            fields=[
                ('ptm_uniprot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('isoform', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.IntegerField(blank=True, null=True)),
                ('aa', models.CharField(blank=True, max_length=1, null=True)),
                ('ptm_type', models.CharField(blank=True, max_length=100, null=True)),
                ('evidence_code', models.CharField(blank=True, max_length=100, null=True)),
                ('source_link', models.CharField(blank=True, max_length=300, null=True)),
                ('ptm_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PTMsDemo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtmsOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptm_uniprot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.IntegerField(blank=True, null=True)),
                ('aa', models.CharField(blank=True, max_length=1, null=True)),
                ('ptm_type', models.CharField(blank=True, max_length=100, null=True)),
                ('source_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'PTMs_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeqCanonical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('sequence', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Seq_canonical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('isoform', models.TextField(blank=True, null=True)),
                ('sequence', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Sequences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signalpeptide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_uniprot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signal_peptide', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'SignalPeptide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StringAcAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_id', models.CharField(blank=True, db_column='Str_id', max_length=25, null=True)),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'String_AC_all',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StringIdGeneName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_id', models.CharField(blank=True, max_length=20, null=True)),
                ('gene_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'string_id_gene_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StringidToUniprot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('str_id', models.CharField(blank=True, db_column='Str_id', max_length=25, null=True)),
            ],
            options={
                'db_table': 'StringID_to_Uniprot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StringInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_p1', models.CharField(blank=True, max_length=20, null=True)),
                ('string_p2', models.CharField(blank=True, max_length=20, null=True)),
                ('combined_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'String_int',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topodom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topology', models.CharField(blank=True, max_length=30, null=True)),
                ('topo_start', models.IntegerField(blank=True, null=True)),
                ('topo_end', models.IntegerField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TopoDom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transmem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('tm_start', models.IntegerField(blank=True, null=True)),
                ('tm_end', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('eco', models.CharField(blank=True, max_length=15, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TransMem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uniprotstringgenename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('string_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'UniprotStringGeneName',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variantlinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'VariantLinks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('var_uniprot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('var_pos', models.IntegerField(blank=True, null=True)),
                ('aa_original', models.CharField(blank=True, max_length=2, null=True)),
                ('aa_substituion', models.CharField(blank=True, max_length=2, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('protein_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variantsdemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_id', models.CharField(blank=True, max_length=100, null=True)),
                ('var_uniprot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('var_pos', models.IntegerField(blank=True, null=True)),
                ('aa_original', models.CharField(blank=True, max_length=2, null=True)),
                ('aa_substituion', models.CharField(blank=True, max_length=2, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'VariantsDemo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Basicbackup',
        ),
        migrations.DeleteModel(
            name='Sigpep',
        ),
    ]
