# Generated by Django 3.2 on 2022-02-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basicinfo2',
            fields=[
                ('uniprot_id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('protein_link', models.TextField(blank=True, null=True)),
                ('protein_name', models.TextField(blank=True, null=True)),
                ('gene_name', models.TextField(blank=True, null=True)),
                ('gene_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BasicInfo2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signalpeptide',
            fields=[
                ('sp_uniprot_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('signal_peptide', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'SignalPeptide',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Basicbackup',
        ),
        migrations.DeleteModel(
            name='Pronameunique',
        ),
        migrations.DeleteModel(
            name='Sigpep',
        ),
    ]
