# Generated by Django 4.0.2 on 2022-02-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_missensevarcomcopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringInteractionUniprot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uniprot_p1', models.CharField(blank=True, max_length=10, null=True)),
                ('string_p1', models.CharField(blank=True, max_length=20, null=True)),
                ('uniprot_p2', models.CharField(blank=True, max_length=10, null=True)),
                ('string_p2', models.CharField(blank=True, max_length=20, null=True)),
                ('combined_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
