# Generated by Django 4.0.1 on 2022-02-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_stringinteractionuniprot'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='missensevarcom',
            table='Missense_Var_Com',
        ),
    ]
