# Generated by Django 4.0.2 on 2022-02-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_delete_missensevarcomcopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geneinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('gene_name', models.TextField(blank=True, null=True)),
                ('gene_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GeneInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Int3DExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prot2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'int3D_extras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interactome3D',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prot1', models.CharField(blank=True, max_length=10, null=True)),
                ('prot2', models.CharField(blank=True, max_length=100, null=True)),
                ('rank_maj', models.IntegerField(blank=True, null=True)),
                ('rank_min', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('pdb_id', models.CharField(blank=True, db_column='PDB_id', max_length=10, null=True)),
                ('bio_unit', models.CharField(blank=True, max_length=5, null=True)),
                ('chain_1', models.CharField(blank=True, max_length=5, null=True)),
                ('model_1', models.CharField(blank=True, max_length=5, null=True)),
                ('seq_ident1', models.IntegerField(blank=True, null=True)),
                ('coverage1', models.IntegerField(blank=True, null=True)),
                ('seq_begin1', models.IntegerField(blank=True, null=True)),
                ('seq_end1', models.IntegerField(blank=True, null=True)),
                ('domain1', models.IntegerField(blank=True, null=True)),
                ('chain_2', models.CharField(blank=True, max_length=5, null=True)),
                ('model_2', models.CharField(blank=True, max_length=5, null=True)),
                ('seq_ident2', models.IntegerField(blank=True, null=True)),
                ('coverage2', models.IntegerField(blank=True, null=True)),
                ('seq_begin2', models.IntegerField(blank=True, null=True)),
                ('seq_end2', models.IntegerField(blank=True, null=True)),
                ('domain2', models.IntegerField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interactome3D',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interactome3D1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prot1', models.CharField(blank=True, max_length=10, null=True)),
                ('prot2', models.CharField(blank=True, max_length=10, null=True)),
                ('rank_maj', models.IntegerField(blank=True, null=True)),
                ('rank_min', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('pdb_id', models.CharField(blank=True, db_column='PDB_id', max_length=10, null=True)),
                ('bio_unit', models.CharField(blank=True, max_length=5, null=True)),
                ('chain_1', models.CharField(blank=True, max_length=5, null=True)),
                ('model_1', models.CharField(blank=True, max_length=5, null=True)),
                ('seq_ident1', models.IntegerField(blank=True, null=True)),
                ('coverage1', models.IntegerField(blank=True, null=True)),
                ('seq_begin1', models.IntegerField(blank=True, null=True)),
                ('seq_end1', models.IntegerField(blank=True, null=True)),
                ('domain1', models.IntegerField(blank=True, null=True)),
                ('chain_2', models.CharField(blank=True, max_length=5, null=True)),
                ('model_2', models.CharField(blank=True, max_length=5, null=True)),
                ('seq_ident2', models.IntegerField(blank=True, null=True)),
                ('coverage2', models.IntegerField(blank=True, null=True)),
                ('seq_begin2', models.IntegerField(blank=True, null=True)),
                ('seq_end2', models.IntegerField(blank=True, null=True)),
                ('domain2', models.IntegerField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interactome3D_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mss3D',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uniprot', models.CharField(blank=True, max_length=10, null=True)),
                ('gene_name', models.TextField(blank=True, null=True)),
                ('structure', models.CharField(blank=True, max_length=10, null=True)),
                ('structure_type', models.CharField(blank=True, max_length=100, null=True)),
                ('posuniprot', models.IntegerField(blank=True, null=True)),
                ('pdbpos', models.IntegerField(blank=True, null=True)),
                ('res_wt', models.CharField(blank=True, max_length=4, null=True)),
                ('res_mut', models.CharField(blank=True, max_length=4, null=True)),
                ('missensepred', models.CharField(blank=True, max_length=50, null=True)),
                ('missense_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('annotationh', models.CharField(blank=True, db_column='annotationH', max_length=100, null=True)),
                ('annotationc', models.CharField(blank=True, db_column='annotationC', max_length=100, null=True)),
                ('maf', models.CharField(blank=True, db_column='MAF', max_length=10, null=True)),
                ('dbsnp', models.CharField(blank=True, max_length=20, null=True)),
                ('sift', models.CharField(blank=True, max_length=20, null=True)),
                ('polyphen', models.CharField(blank=True, max_length=20, null=True)),
                ('ensemble', models.CharField(blank=True, max_length=20, null=True)),
                ('interface', models.CharField(blank=True, max_length=20, null=True)),
                ('pfam', models.CharField(blank=True, max_length=20, null=True)),
                ('missense3did', models.CharField(blank=True, max_length=20, null=True)),
                ('foldx', models.CharField(blank=True, max_length=20, null=True)),
                ('ch37', models.CharField(blank=True, max_length=20, null=True)),
                ('ccr', models.CharField(blank=True, max_length=20, null=True)),
                ('ch38', models.CharField(blank=True, max_length=20, null=True)),
                ('gerp', models.CharField(blank=True, max_length=20, null=True)),
                ('pli', models.CharField(blank=True, db_column='pLI', max_length=20, null=True)),
                ('rvisscore', models.CharField(blank=True, db_column='rvisScore', max_length=20, null=True)),
                ('rvispercent', models.CharField(blank=True, db_column='rvisPercent', max_length=20, null=True)),
            ],
            options={
                'db_table': 'MSS3D',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stringdetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_p1', models.CharField(blank=True, max_length=20, null=True)),
                ('uniprot_p1', models.CharField(blank=True, max_length=10, null=True)),
                ('string_p2', models.CharField(blank=True, max_length=20, null=True)),
                ('uniprot_p2', models.CharField(blank=True, max_length=10, null=True)),
                ('neighbourhood', models.IntegerField(blank=True, null=True)),
                ('fusion', models.IntegerField(blank=True, null=True)),
                ('cooccurence', models.IntegerField(blank=True, null=True)),
                ('coexpression', models.IntegerField(blank=True, null=True)),
                ('experimental', models.IntegerField(blank=True, null=True)),
                ('data_base', models.IntegerField(blank=True, null=True)),
                ('textmining', models.IntegerField(blank=True, null=True)),
                ('combined_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'StringDetailed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stringinteractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_p1', models.CharField(blank=True, max_length=20, null=True)),
                ('string_p2', models.CharField(blank=True, max_length=20, null=True)),
                ('experimental', models.IntegerField(blank=True, null=True)),
                ('data_base', models.IntegerField(blank=True, null=True)),
                ('combined_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'StringInteractions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stringraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_p1', models.CharField(blank=True, max_length=20, null=True)),
                ('string_p2', models.CharField(blank=True, max_length=20, null=True)),
                ('neighbourhood', models.IntegerField(blank=True, null=True)),
                ('fusion', models.IntegerField(blank=True, null=True)),
                ('cooccurence', models.IntegerField(blank=True, null=True)),
                ('coexpression', models.IntegerField(blank=True, null=True)),
                ('experimental', models.IntegerField(blank=True, null=True)),
                ('data_base', models.IntegerField(blank=True, null=True)),
                ('textmining', models.IntegerField(blank=True, null=True)),
                ('combined_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'StringRaw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stringtouniprot',
            fields=[
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('string_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'StringToUniprot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topocellcomp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('topo_link', models.TextField(blank=True, null=True)),
                ('topo_label', models.TextField(blank=True, null=True)),
                ('cellcomp_link', models.TextField(blank=True, null=True)),
                ('cellcomp_label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TopoCellComp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransmemOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_uniprot_id', models.CharField(blank=True, max_length=10, null=True)),
                ('tm_start', models.IntegerField(blank=True, null=True)),
                ('tm_end', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('eco', models.CharField(blank=True, max_length=15, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TransMem_old',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Domainnameunique',
        ),
        migrations.DeleteModel(
            name='Domains2',
        ),
        migrations.DeleteModel(
            name='Genelink',
        ),
        migrations.DeleteModel(
            name='Genename',
        ),
        migrations.DeleteModel(
            name='Pfamdemo',
        ),
        migrations.DeleteModel(
            name='PtmsOld',
        ),
        migrations.DeleteModel(
            name='StringAcAll',
        ),
        migrations.DeleteModel(
            name='StringIdGeneName',
        ),
        migrations.DeleteModel(
            name='StringidToUniprot',
        ),
        migrations.DeleteModel(
            name='StringInt',
        ),
        migrations.DeleteModel(
            name='Uniprotstringgenename',
        ),
        migrations.DeleteModel(
            name='Variantsdemo',
        ),
        migrations.AlterModelTable(
            name='stringinteractionuniprot',
            table='string_interaction_uniprot',
        ),
    ]
